export {Login as ScreenLogin} from './Login'
export {Register as ScreenRegister} from './Register'
export {Perfil as ScreenPerfil} from './Perfil'
export {Mensagem as ScreenMensagem} from './Mensagem'
export {CadMessage as ScreenCadMensagem} from './CadMensagem'
export {Camera as ScreenCamera} from './Camera'
export {Imagens as ScreenImagens} from './Imagens'
export {QrCode as ScreenQrCode} from './QrCode'